//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace ServiceReference1
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://soap.sparkjavasoap.avathartech.com/", ConfigurationName="ServiceReference1.AcademicoWebService")]
    public interface AcademicoWebService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://soap.sparkjavasoap.avathartech.com/AcademicoWebService/holaMundoRequest", ReplyAction="http://soap.sparkjavasoap.avathartech.com/AcademicoWebService/holaMundoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.holaMundoResponse> holaMundoAsync(ServiceReference1.holaMundoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://soap.sparkjavasoap.avathartech.com/AcademicoWebService/getEstudianteReques" +
            "t", ReplyAction="http://soap.sparkjavasoap.avathartech.com/AcademicoWebService/getEstudianteRespon" +
            "se")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.getEstudianteResponse> getEstudianteAsync(ServiceReference1.getEstudianteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://soap.sparkjavasoap.avathartech.com/AcademicoWebService/getAsignaturaReques" +
            "t", ReplyAction="http://soap.sparkjavasoap.avathartech.com/AcademicoWebService/getAsignaturaRespon" +
            "se")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.getAsignaturaResponse> getAsignaturaAsync(ServiceReference1.getAsignaturaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://soap.sparkjavasoap.avathartech.com/AcademicoWebService/getAllEstudianteReq" +
            "uest", ReplyAction="http://soap.sparkjavasoap.avathartech.com/AcademicoWebService/getAllEstudianteRes" +
            "ponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.getAllEstudianteResponse> getAllEstudianteAsync(ServiceReference1.getAllEstudianteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://soap.sparkjavasoap.avathartech.com/AcademicoWebService/getProfesorRequest", ReplyAction="http://soap.sparkjavasoap.avathartech.com/AcademicoWebService/getProfesorResponse" +
            "")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.getProfesorResponse> getProfesorAsync(ServiceReference1.getProfesorRequest request);
        void holaMundoAsync();
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="holaMundo", WrapperNamespace="http://soap.sparkjavasoap.avathartech.com/", IsWrapped=true)]
    public partial class holaMundoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.sparkjavasoap.avathartech.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public holaMundoRequest()
        {
        }
        
        public holaMundoRequest(string arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="holaMundoResponse", WrapperNamespace="http://soap.sparkjavasoap.avathartech.com/", IsWrapped=true)]
    public partial class holaMundoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.sparkjavasoap.avathartech.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public holaMundoResponse()
        {
        }
        
        public holaMundoResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.sparkjavasoap.avathartech.com/")]
    public partial class estudiante
    {
        
        private int matriculaField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int matricula
        {
            get
            {
                return this.matriculaField;
            }
            set
            {
                this.matriculaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.sparkjavasoap.avathartech.com/")]
    public partial class profesor
    {
        
        private string cedulaField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string cedula
        {
            get
            {
                return this.cedulaField;
            }
            set
            {
                this.cedulaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.sparkjavasoap.avathartech.com/")]
    public partial class asignatura
    {
        
        private string claveField;
        
        private estudiante[] estudiantesField;
        
        private int grupoField;
        
        private int idField;
        
        private string nombreField;
        
        private profesor profesorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string clave
        {
            get
            {
                return this.claveField;
            }
            set
            {
                this.claveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("estudiantes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public estudiante[] estudiantes
        {
            get
            {
                return this.estudiantesField;
            }
            set
            {
                this.estudiantesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int grupo
        {
            get
            {
                return this.grupoField;
            }
            set
            {
                this.grupoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public profesor profesor
        {
            get
            {
                return this.profesorField;
            }
            set
            {
                this.profesorField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getEstudiante", WrapperNamespace="http://soap.sparkjavasoap.avathartech.com/", IsWrapped=true)]
    public partial class getEstudianteRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.sparkjavasoap.avathartech.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        public getEstudianteRequest()
        {
        }
        
        public getEstudianteRequest(int arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getEstudianteResponse", WrapperNamespace="http://soap.sparkjavasoap.avathartech.com/", IsWrapped=true)]
    public partial class getEstudianteResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.sparkjavasoap.avathartech.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference1.estudiante @return;
        
        public getEstudianteResponse()
        {
        }
        
        public getEstudianteResponse(ServiceReference1.estudiante @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAsignatura", WrapperNamespace="http://soap.sparkjavasoap.avathartech.com/", IsWrapped=true)]
    public partial class getAsignaturaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.sparkjavasoap.avathartech.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        public getAsignaturaRequest()
        {
        }
        
        public getAsignaturaRequest(int arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAsignaturaResponse", WrapperNamespace="http://soap.sparkjavasoap.avathartech.com/", IsWrapped=true)]
    public partial class getAsignaturaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.sparkjavasoap.avathartech.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference1.asignatura @return;
        
        public getAsignaturaResponse()
        {
        }
        
        public getAsignaturaResponse(ServiceReference1.asignatura @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllEstudiante", WrapperNamespace="http://soap.sparkjavasoap.avathartech.com/", IsWrapped=true)]
    public partial class getAllEstudianteRequest
    {
        
        public getAllEstudianteRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllEstudianteResponse", WrapperNamespace="http://soap.sparkjavasoap.avathartech.com/", IsWrapped=true)]
    public partial class getAllEstudianteResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.sparkjavasoap.avathartech.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference1.estudiante[] @return;
        
        public getAllEstudianteResponse()
        {
        }
        
        public getAllEstudianteResponse(ServiceReference1.estudiante[] @return)
        {
            this.@return = @return;
        }

        public static implicit operator List<object>(getAllEstudianteResponse v)
        {
            throw new NotImplementedException();
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getProfesor", WrapperNamespace="http://soap.sparkjavasoap.avathartech.com/", IsWrapped=true)]
    public partial class getProfesorRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.sparkjavasoap.avathartech.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public getProfesorRequest()
        {
        }
        
        public getProfesorRequest(string arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getProfesorResponse", WrapperNamespace="http://soap.sparkjavasoap.avathartech.com/", IsWrapped=true)]
    public partial class getProfesorResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.sparkjavasoap.avathartech.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference1.profesor @return;
        
        public getProfesorResponse()
        {
        }
        
        public getProfesorResponse(ServiceReference1.profesor @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public interface AcademicoWebServiceChannel : ServiceReference1.AcademicoWebService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public partial class AcademicoWebServiceClient : System.ServiceModel.ClientBase<ServiceReference1.AcademicoWebService>, ServiceReference1.AcademicoWebService
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public AcademicoWebServiceClient() : 
                base(AcademicoWebServiceClient.GetDefaultBinding(), AcademicoWebServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.AcademicoWebServicePort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AcademicoWebServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(AcademicoWebServiceClient.GetBindingForEndpoint(endpointConfiguration), AcademicoWebServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AcademicoWebServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(AcademicoWebServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AcademicoWebServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(AcademicoWebServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AcademicoWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.holaMundoResponse> ServiceReference1.AcademicoWebService.holaMundoAsync(ServiceReference1.holaMundoRequest request)
        {
            return base.Channel.holaMundoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.holaMundoResponse> holaMundoAsync(string arg0)
        {
            ServiceReference1.holaMundoRequest inValue = new ServiceReference1.holaMundoRequest();
            inValue.arg0 = arg0;
            return ((ServiceReference1.AcademicoWebService)(this)).holaMundoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.getEstudianteResponse> ServiceReference1.AcademicoWebService.getEstudianteAsync(ServiceReference1.getEstudianteRequest request)
        {
            return base.Channel.getEstudianteAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.getEstudianteResponse> getEstudianteAsync(int arg0)
        {
            ServiceReference1.getEstudianteRequest inValue = new ServiceReference1.getEstudianteRequest();
            inValue.arg0 = arg0;
            return ((ServiceReference1.AcademicoWebService)(this)).getEstudianteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.getAsignaturaResponse> ServiceReference1.AcademicoWebService.getAsignaturaAsync(ServiceReference1.getAsignaturaRequest request)
        {
            return base.Channel.getAsignaturaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.getAsignaturaResponse> getAsignaturaAsync(int arg0)
        {
            ServiceReference1.getAsignaturaRequest inValue = new ServiceReference1.getAsignaturaRequest();
            inValue.arg0 = arg0;
            return ((ServiceReference1.AcademicoWebService)(this)).getAsignaturaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.getAllEstudianteResponse> ServiceReference1.AcademicoWebService.getAllEstudianteAsync(ServiceReference1.getAllEstudianteRequest request)
        {
            return base.Channel.getAllEstudianteAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.getAllEstudianteResponse> getAllEstudianteAsync()
        {
            ServiceReference1.getAllEstudianteRequest inValue = new ServiceReference1.getAllEstudianteRequest();
            return ((ServiceReference1.AcademicoWebService)(this)).getAllEstudianteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.getProfesorResponse> ServiceReference1.AcademicoWebService.getProfesorAsync(ServiceReference1.getProfesorRequest request)
        {
            return base.Channel.getProfesorAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.getProfesorResponse> getProfesorAsync(string arg0)
        {
            ServiceReference1.getProfesorRequest inValue = new ServiceReference1.getProfesorRequest();
            inValue.arg0 = arg0;
            return ((ServiceReference1.AcademicoWebService)(this)).getProfesorAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.AcademicoWebServicePort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.AcademicoWebServicePort))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:7777/ws");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return AcademicoWebServiceClient.GetBindingForEndpoint(EndpointConfiguration.AcademicoWebServicePort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return AcademicoWebServiceClient.GetEndpointAddress(EndpointConfiguration.AcademicoWebServicePort);
        }

        public void holaMundoAsync()
        {
            throw new System.NotImplementedException();
        }

        public enum EndpointConfiguration
        {
            
            AcademicoWebServicePort,
        }
    }
}
